### ISSUE TITLE
Where do I get the library?

### ISSUE THREAD

**Issue by Bummibaer** [ffcrg/ecwmbus#1]
Hey,
where do I get information and source of the WMBUSHCI.dll?

regards Steffen

**Comment by ffcrg** [comment]
Hey
the binary WMBUSHCI.DLL is from the manufacturer of the wM-Bus Stick (http://www.wireless-solutions.de) - I don't have the source.

Documentation on the command interface of the stick is available at : http://www.wireless-solutions.de/images/stories/downloads/Gateways%20and%20USB%20Adapter/iM871A-usb/WMBus_HCI_Spec_V1_5.pdf

Best regards
ffcrg
